<template>
  <div class="grid" style="height: 100%;">
    <div id="map"></div>
    <app-menu
        v-on:showTileLayer="showTileLayer"
        v-on:pushOrganismId="getFeature"
        v-on:removeOrganism="removeOrganism"
        v-on:showArcticTerritory="showArcticTerritory"
        v-on:showOOPT="showOOPT"
    />
  </div>
</template>

<script>
import L from "leaflet";
import AppMenu from "@/components/app-menu";
import "leaflet.pattern"

export default {
  name: 'main-page',

  data() {
    return {
      features: [],
      layers: [],
      map: {},
      arcticTerritoryLayer: {},
      lastLayer: {},
      cmr: {},
      zones: {},
      oopt: {},
      lgndCmr: {}
    }
  },

  mounted() {

    // Creating a Layer object
    const osmMap = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      minZoom: 0,
      maxZoom: 7,
      attribution: 'Map provider OSM'
    });

    this.cmr = L.tileLayer('/images/cmr/{z}/{x}/{y}.png', {
      minZoom: 0,
      maxZoom: 7,
      tms: false,
      attribution: 'Generated by TilesXYZ'
    })

    this.cmr.on('add', this.lgndCmrAdd)
    this.cmr.on('remove', this.lgndCmrRemove)

    this.zones = L.tileLayer("/images/zones/{z}/{x}/{y}.png", {
      minZoom: 0,
      maxZoom: 7,
      tms: false,
      attribution: 'Generated by TilesXYZ'
    })

    // const baseLayers = {
    //   'OSM Карта': osmMap,
    //
    // }
    //
    // const overlayLayers = {
    //   'ЦМР': cmr,
    //   'Зоны и типы поясности растительности России': oopt
    // }

    this.map = new L.Map('map', {
      center: [70.76, 104.68],
      zoom: 4,
      layers: [osmMap]
      //crs: L.CRS.EPSG3857
    })

    // L.control.layers(baseLayers, overlayLayers).addTo(this.map)

    // Adding layer to the map
    // this.map.addLayer(layer);

    const lgnd = L.control({
      position: "bottomright"
    });

    lgnd.onAdd = function () {
      let lgndDiv = L.DomUtil.create('div', 'infolgnd'),
          labels = [];
      labels.push('<b>Редкость</b>')
      labels.push('<div class="circle" style="background: #000000; text-align: center; color: darkgray"> 0')
      labels.push('<div class="circle" style="background: #ff0101; color: black"> 1')
      labels.push('<div class="circle" style="background: #f37101"> 2')
      labels.push('<div class="circle" style="background: #eaac00"> 3')
      labels.push('<div class="circle" style="background: #e6d600"> 4')
      labels.push('<div class="circle" style="background: #deff00"> 5')
      labels.push('<div class="circle" style="background: #acff01"> 6')
      labels.push('<div class="circle" style="background: #2cff01"> 7')
      lgndDiv.innerHTML = labels.join('<br>')

      return lgndDiv
    }

    lgnd.addTo(this.map)

    // Легенда для физической карты
    const lgndCmr = L.control({
      position: "topleft"
    });

    lgndCmr.onAdd = function () {
      let lgndDiv = L.DomUtil.create('div', 'infolgnd'),
          labels = [];
      labels.push('<b>Высоты</b>')
      labels.push('<div class="circle" style="background: #40aa51; text-align: center"> -200')
      labels.push('<div class="circle" style="background: #6bbb58; color: black"> -100')
      labels.push('<div class="circle" style="background: #90cf6d"> -50')
      labels.push('<div class="circle" style="background: #b2e275"> 0')
      labels.push('<div class="circle" style="background: #cee795"> 50')
      labels.push('<div class="circle" style="background: #e6f4a3"> 100')
      labels.push('<div class="circle" style="background: #ffffbe"> 200')
      labels.push('<div class="circle" style="background: #fde9a3"> 300')
      labels.push('<div class="circle" style="background: #fecf91"> 400')
      labels.push('<div class="circle" style="background: #f7b673"> 500')
      labels.push('<div class="circle" style="background: #fd955d"> 1000')
      labels.push('<div class="circle" style="background: #ed7146"> 1500')
      labels.push('<div class="circle" style="background: #e54232"> 2000')
      labels.push('<div class="circle" style="background: #d11c1b"> 2500')
      lgndDiv.innerHTML = labels.join('<br>')

      return lgndDiv
    }

    this.lgndCmr = lgndCmr

    const tooltip = L.control({
      position: "bottomleft"
    })

    tooltip.onAdd = function () {
      const tooltipDiv = L.DomUtil.create('div', 'tooltip')
      tooltipDiv.style.background = "white"
      tooltipDiv.style.fontSize = "12pt"
      tooltipDiv.style.border = "1px solid black"
      return tooltipDiv
    }

    tooltip.addTo(this.map)


    this.getArcticTerritory()
    this.getOOPT()
  },

  methods: {
    async getArcticTerritory() {
      const response = await fetch("/api/v1/arctic-territory")
      const json = await response.json()
      json.features.forEach(feature => this.antimeridian(feature.geometry.coordinates))

      const layer = L.geoJSON(json, {
        style: {
          color: "#1a31db",
          fillOpacity: 0
        }
      })

      this.arcticTerritoryLayer = layer
      layer.addTo(this.map)
    },

    async getOOPT() {
      const response = await fetch("/json/oopt.json")
      const json = await response.json()
      json.features.forEach(feature => this.antimeridian(feature.geometry.coordinates))

      const layer = L.geoJSON(json, {
            style: {
              color: "#8a2be2",
              fillOpacity: 0.3
            },
            onEachFeature: function (feature, layer) {
              layer.bindPopup(feature.properties.name)
            }
          }
      )

      this.oopt = layer
    },

    async getFeature(id) {
      const response = await fetch(`/api/v1/animals/${id}`)
      const json = await response.json()
      this.antimeridian(json.geometry.coordinates)
      const vue = this

      let pattern = new L.StripePattern({angle: 45, weight: 2, color: 'blue', opacity: 0.5})
      pattern.addTo(this.map)

      const layer = L.geoJSON(json, {
        style: function (feature) {
          const rare = feature.properties.rare[0]
          switch (rare) {
            case  "1":
              return {color: "#ff0101", fillPattern: pattern, fillOpacity: 1.0}
            case "2":
              return {color: "#f37101"}
            case "3":
              return {color: "#eaac00"}
            case "4":
              return {color: "#e6d600"}
            case "5":
              return {color: "#deff00"}
            case "6":
              return {color: "#acff01"}
            case "7":
              return {color: "#2cff01"}
            case "0":
              return {color: "#000000"}
          }
        },
        onEachFeature: function (feature, layer) {
          //layer.bindPopup(feature.properties.nameRu)
          //layer.bindTooltip(feature.properties.nameRu)
          layer.on('click', function () {
            layer.bringToBack()
            vue.arcticTerritoryLayer.bringToBack()
            vue.oopt.bringToBack()
          })

          const defaultColor = layer.options.color
          const tooltip = document.querySelector(".tooltip")
          layer.on('mouseover', function () {
            layer.bringToFront()
            //layer.openPopup()
            layer.setStyle({weight: 3, color: "black", fillColor: defaultColor})
            tooltip.innerHTML = feature.properties.nameRu + "<br> Редкость: " + feature.properties.rare
          })

          layer.on('mouseout', function () {
            //layer.closePopup()
            tooltip.innerHTML = ""
            layer.setStyle({weight: 3, color: defaultColor})
          })
        }
      })

      this.layers.push({id: id, layer: layer})
      layer.addTo(this.map)
    },

    removeOrganism(id) {
      this.layers.forEach(layer => {
            if (layer.id === id) {
              this.map.removeLayer(layer.layer)
            }
          }
      )
    },

    showTileLayer(layer) {
      switch (layer) {
        case "По умолчанию":
          this.map.removeLayer(this.cmr)
          this.map.removeLayer(this.zones)
          break
        case "Зоны и типы поясности растительности России":
          this.map.removeLayer(this.cmr)
          this.zones.addTo(this.map)
          break
        case "Физическая карта":
          this.map.removeLayer(this.zones)
          this.cmr.addTo(this.map)
          break
      }
    },

    showArcticTerritory(display) {
      if (display) {
        this.arcticTerritoryLayer.addTo(this.map)
      } else {
        this.map.removeLayer(this.arcticTerritoryLayer)
      }
    },

    showOOPT(display) {
      if (display) {
        this.oopt.addTo(this.map)
      } else {
        this.map.removeLayer(this.oopt)
      }
    },

    lgndCmrAdd() {
      this.lgndCmr.addTo(this.map)
    },

    lgndCmrRemove() {
      this.lgndCmr.remove(this.map)
    },

    antimeridian(elem) {
      if (Array.isArray(elem)) {
        for (var i = 0; i < elem.length; i++) {
          if (Array.isArray(elem[i][0])) {
            this.antimeridian(elem[i]);
          } else {
            if (elem[i][0] < 0) {
              elem[i][0] = 180 + (180 + elem[i][0]);
            }
          }
        }
      }
    }
  },

  components: {
    AppMenu
  }
}
</script>

<style scoped>
@import "/node_modules/leaflet/dist/leaflet.css";

#map {
  height: 100vh;
}

.circle {
  clip-path: circle(50%);
  height: 5em;
  width: 5em;
  text-align: center;
}

div.grid {
  display: grid;
  grid-template-columns: 2fr 1fr;
}
</style>
